"""Add last_extension_date to PatientBHYT

Revision ID: 1fb7607dcce7
Revises: 
Create Date: 2026-05-08 15:22:06.726111

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1fb7607dcce7'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('idx_account_email'), table_name='account')
    op.create_index('idx_account_email', 'account', ['email'], unique=False)
    op.create_index(op.f('ix_account_email'), 'account', ['email'], unique=True)
    op.add_column('appointment', sa.Column('locked_until', sa.TIMESTAMP(), nullable=True))
    op.add_column('doctor', sa.Column('hourly_consultation_fee', sa.Integer(), nullable=False))
    op.create_unique_constraint(None, 'medical_record', ['appointment_id'])
    op.add_column('patient_bhyt', sa.Column('last_extension_date', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('patient_bhyt', 'last_extension_date')
    op.drop_constraint(None, 'medical_record', type_='unique')
    op.drop_column('doctor', 'hourly_consultation_fee')
    op.drop_column('appointment', 'locked_until')
    op.drop_index(op.f('ix_account_email'), table_name='account')
    op.drop_index('idx_account_email', table_name='account')
    op.create_index(op.f('idx_account_email'), 'account', ['email'], unique=True)
    # ### end Alembic commands ###
